language: java

script:
  - chmod u+x build-package.sh
  - ./build-package.sh
  
  
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start


# cache the build tool's caches
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

sudo: false

