### Project specific config ###
language: generic


  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

### Generic setup follows ###
script:
  - chmod u+x build-package.sh
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

sudo: false

dist: trusty
